version: '3.7'

services:
  task-tracker-react-postgres:
    image: postgres:latest
    volumes:
      - ./pg_data:/var/lib/postgresql
    networks:
      - default
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
  task-tracker-react-backend:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - task-tracker-react-postgres